#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLy_DoAn_TNTH
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DAMH")]
	public partial class DAMHDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNhomSV(NhomSV instance);
    partial void UpdateNhomSV(NhomSV instance);
    partial void DeleteNhomSV(NhomSV instance);
    partial void InsertPhanThietBi(PhanThietBi instance);
    partial void UpdatePhanThietBi(PhanThietBi instance);
    partial void DeletePhanThietBi(PhanThietBi instance);
    partial void InsertKhoa(Khoa instance);
    partial void UpdateKhoa(Khoa instance);
    partial void DeleteKhoa(Khoa instance);
    partial void InsertDeAn(DeAn instance);
    partial void UpdateDeAn(DeAn instance);
    partial void DeleteDeAn(DeAn instance);
    partial void InsertDangKyDC(DangKyDC instance);
    partial void UpdateDangKyDC(DangKyDC instance);
    partial void DeleteDangKyDC(DangKyDC instance);
    partial void InsertDangKyHC(DangKyHC instance);
    partial void UpdateDangKyHC(DangKyHC instance);
    partial void DeleteDangKyHC(DangKyHC instance);
    partial void InsertDangKyTapSDTB(DangKyTapSDTB instance);
    partial void UpdateDangKyTapSDTB(DangKyTapSDTB instance);
    partial void DeleteDangKyTapSDTB(DangKyTapSDTB instance);
    partial void InsertDangKyTN(DangKyTN instance);
    partial void UpdateDangKyTN(DangKyTN instance);
    partial void DeleteDangKyTN(DangKyTN instance);
    partial void InsertDungCu(DungCu instance);
    partial void UpdateDungCu(DungCu instance);
    partial void DeleteDungCu(DungCu instance);
    partial void InsertGiaoVienHD(GiaoVienHD instance);
    partial void UpdateGiaoVienHD(GiaoVienHD instance);
    partial void DeleteGiaoVienHD(GiaoVienHD instance);
    partial void InsertGiaoVienQLPTN(GiaoVienQLPTN instance);
    partial void UpdateGiaoVienQLPTN(GiaoVienQLPTN instance);
    partial void DeleteGiaoVienQLPTN(GiaoVienQLPTN instance);
    partial void InsertHoaChat(HoaChat instance);
    partial void UpdateHoaChat(HoaChat instance);
    partial void DeleteHoaChat(HoaChat instance);
    partial void InsertPhanThietBi_LT(PhanThietBi_LT instance);
    partial void UpdatePhanThietBi_LT(PhanThietBi_LT instance);
    partial void DeletePhanThietBi_LT(PhanThietBi_LT instance);
    partial void InsertPhongThiNghiem(PhongThiNghiem instance);
    partial void UpdatePhongThiNghiem(PhongThiNghiem instance);
    partial void DeletePhongThiNghiem(PhongThiNghiem instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    partial void InsertThietBi(ThietBi instance);
    partial void UpdateThietBi(ThietBi instance);
    partial void DeleteThietBi(ThietBi instance);
    #endregion
		
		public DAMHDataContext() : 
				base(global::QuanLy_DoAn_TNTH.Properties.Settings.Default.DAMHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DAMHDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAMHDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAMHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DAMHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NhomSV> NhomSVs
		{
			get
			{
				return this.GetTable<NhomSV>();
			}
		}
		
		public System.Data.Linq.Table<PhanThietBi> PhanThietBis
		{
			get
			{
				return this.GetTable<PhanThietBi>();
			}
		}
		
		public System.Data.Linq.Table<Khoa> Khoas
		{
			get
			{
				return this.GetTable<Khoa>();
			}
		}
		
		public System.Data.Linq.Table<DeAn> DeAns
		{
			get
			{
				return this.GetTable<DeAn>();
			}
		}
		
		public System.Data.Linq.Table<DangKyDC> DangKyDCs
		{
			get
			{
				return this.GetTable<DangKyDC>();
			}
		}
		
		public System.Data.Linq.Table<DangKyHC> DangKyHCs
		{
			get
			{
				return this.GetTable<DangKyHC>();
			}
		}
		
		public System.Data.Linq.Table<DangKyTapSDTB> DangKyTapSDTBs
		{
			get
			{
				return this.GetTable<DangKyTapSDTB>();
			}
		}
		
		public System.Data.Linq.Table<DangKyTN> DangKyTNs
		{
			get
			{
				return this.GetTable<DangKyTN>();
			}
		}
		
		public System.Data.Linq.Table<DungCu> DungCus
		{
			get
			{
				return this.GetTable<DungCu>();
			}
		}
		
		public System.Data.Linq.Table<GiaoVienHD> GiaoVienHDs
		{
			get
			{
				return this.GetTable<GiaoVienHD>();
			}
		}
		
		public System.Data.Linq.Table<GiaoVienQLPTN> GiaoVienQLPTNs
		{
			get
			{
				return this.GetTable<GiaoVienQLPTN>();
			}
		}
		
		public System.Data.Linq.Table<HoaChat> HoaChats
		{
			get
			{
				return this.GetTable<HoaChat>();
			}
		}
		
		public System.Data.Linq.Table<PhanThietBi_LT> PhanThietBi_LTs
		{
			get
			{
				return this.GetTable<PhanThietBi_LT>();
			}
		}
		
		public System.Data.Linq.Table<PhongThiNghiem> PhongThiNghiems
		{
			get
			{
				return this.GetTable<PhongThiNghiem>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
		
		public System.Data.Linq.Table<ThietBi> ThietBis
		{
			get
			{
				return this.GetTable<ThietBi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomSV")]
	public partial class NhomSV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _TenNhom;
		
		private EntitySet<DeAn> _DeAns;
		
		private EntitySet<DangKyDC> _DangKyDCs;
		
		private EntitySet<DangKyHC> _DangKyHCs;
		
		private EntitySet<DangKyTapSDTB> _DangKyTapSDTBs;
		
		private EntitySet<DangKyTN> _DangKyTNs;
		
		private EntitySet<SinhVien> _SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    #endregion
		
		public NhomSV()
		{
			this._DeAns = new EntitySet<DeAn>(new Action<DeAn>(this.attach_DeAns), new Action<DeAn>(this.detach_DeAns));
			this._DangKyDCs = new EntitySet<DangKyDC>(new Action<DangKyDC>(this.attach_DangKyDCs), new Action<DangKyDC>(this.detach_DangKyDCs));
			this._DangKyHCs = new EntitySet<DangKyHC>(new Action<DangKyHC>(this.attach_DangKyHCs), new Action<DangKyHC>(this.detach_DangKyHCs));
			this._DangKyTapSDTBs = new EntitySet<DangKyTapSDTB>(new Action<DangKyTapSDTB>(this.attach_DangKyTapSDTBs), new Action<DangKyTapSDTB>(this.detach_DangKyTapSDTBs));
			this._DangKyTNs = new EntitySet<DangKyTN>(new Action<DangKyTN>(this.attach_DangKyTNs), new Action<DangKyTN>(this.detach_DangKyTNs));
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this.OnTenNhomChanging(value);
					this.SendPropertyChanging();
					this._TenNhom = value;
					this.SendPropertyChanged("TenNhom");
					this.OnTenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSV_DeAn", Storage="_DeAns", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<DeAn> DeAns
		{
			get
			{
				return this._DeAns;
			}
			set
			{
				this._DeAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSV_DangKyDC", Storage="_DangKyDCs", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<DangKyDC> DangKyDCs
		{
			get
			{
				return this._DangKyDCs;
			}
			set
			{
				this._DangKyDCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSV_DangKyHC", Storage="_DangKyHCs", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<DangKyHC> DangKyHCs
		{
			get
			{
				return this._DangKyHCs;
			}
			set
			{
				this._DangKyHCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSV_DangKyTapSDTB", Storage="_DangKyTapSDTBs", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<DangKyTapSDTB> DangKyTapSDTBs
		{
			get
			{
				return this._DangKyTapSDTBs;
			}
			set
			{
				this._DangKyTapSDTBs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSV_DangKyTN", Storage="_DangKyTNs", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<DangKyTN> DangKyTNs
		{
			get
			{
				return this._DangKyTNs;
			}
			set
			{
				this._DangKyTNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSV_SinhVien", Storage="_SinhViens", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeAns(DeAn entity)
		{
			this.SendPropertyChanging();
			entity.NhomSV = this;
		}
		
		private void detach_DeAns(DeAn entity)
		{
			this.SendPropertyChanging();
			entity.NhomSV = null;
		}
		
		private void attach_DangKyDCs(DangKyDC entity)
		{
			this.SendPropertyChanging();
			entity.NhomSV = this;
		}
		
		private void detach_DangKyDCs(DangKyDC entity)
		{
			this.SendPropertyChanging();
			entity.NhomSV = null;
		}
		
		private void attach_DangKyHCs(DangKyHC entity)
		{
			this.SendPropertyChanging();
			entity.NhomSV = this;
		}
		
		private void detach_DangKyHCs(DangKyHC entity)
		{
			this.SendPropertyChanging();
			entity.NhomSV = null;
		}
		
		private void attach_DangKyTapSDTBs(DangKyTapSDTB entity)
		{
			this.SendPropertyChanging();
			entity.NhomSV = this;
		}
		
		private void detach_DangKyTapSDTBs(DangKyTapSDTB entity)
		{
			this.SendPropertyChanging();
			entity.NhomSV = null;
		}
		
		private void attach_DangKyTNs(DangKyTN entity)
		{
			this.SendPropertyChanging();
			entity.NhomSV = this;
		}
		
		private void detach_DangKyTNs(DangKyTN entity)
		{
			this.SendPropertyChanging();
			entity.NhomSV = null;
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.NhomSV = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.NhomSV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanThietBi")]
	public partial class PhanThietBi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _NgayPhan;
		
		private string _MaPTN;
		
		private string _MaTB;
		
		private System.Nullable<int> _SoLuongPhan_TB;
		
		private EntityRef<PhongThiNghiem> _PhongThiNghiem;
		
		private EntityRef<ThietBi> _ThietBi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNgayPhanChanging(System.DateTime value);
    partial void OnNgayPhanChanged();
    partial void OnMaPTNChanging(string value);
    partial void OnMaPTNChanged();
    partial void OnMaTBChanging(string value);
    partial void OnMaTBChanged();
    partial void OnSoLuongPhan_TBChanging(System.Nullable<int> value);
    partial void OnSoLuongPhan_TBChanged();
    #endregion
		
		public PhanThietBi()
		{
			this._PhongThiNghiem = default(EntityRef<PhongThiNghiem>);
			this._ThietBi = default(EntityRef<ThietBi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayPhan", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NgayPhan
		{
			get
			{
				return this._NgayPhan;
			}
			set
			{
				if ((this._NgayPhan != value))
				{
					this.OnNgayPhanChanging(value);
					this.SendPropertyChanging();
					this._NgayPhan = value;
					this.SendPropertyChanged("NgayPhan");
					this.OnNgayPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPTN", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPTN
		{
			get
			{
				return this._MaPTN;
			}
			set
			{
				if ((this._MaPTN != value))
				{
					if (this._PhongThiNghiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPTNChanging(value);
					this.SendPropertyChanging();
					this._MaPTN = value;
					this.SendPropertyChanged("MaPTN");
					this.OnMaPTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTB", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTB
		{
			get
			{
				return this._MaTB;
			}
			set
			{
				if ((this._MaTB != value))
				{
					if (this._ThietBi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTBChanging(value);
					this.SendPropertyChanging();
					this._MaTB = value;
					this.SendPropertyChanged("MaTB");
					this.OnMaTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongPhan_TB", DbType="Int")]
		public System.Nullable<int> SoLuongPhan_TB
		{
			get
			{
				return this._SoLuongPhan_TB;
			}
			set
			{
				if ((this._SoLuongPhan_TB != value))
				{
					this.OnSoLuongPhan_TBChanging(value);
					this.SendPropertyChanging();
					this._SoLuongPhan_TB = value;
					this.SendPropertyChanged("SoLuongPhan_TB");
					this.OnSoLuongPhan_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongThiNghiem_PhanThietBi", Storage="_PhongThiNghiem", ThisKey="MaPTN", OtherKey="MaPTN", IsForeignKey=true)]
		public PhongThiNghiem PhongThiNghiem
		{
			get
			{
				return this._PhongThiNghiem.Entity;
			}
			set
			{
				PhongThiNghiem previousValue = this._PhongThiNghiem.Entity;
				if (((previousValue != value) 
							|| (this._PhongThiNghiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongThiNghiem.Entity = null;
						previousValue.PhanThietBis.Remove(this);
					}
					this._PhongThiNghiem.Entity = value;
					if ((value != null))
					{
						value.PhanThietBis.Add(this);
						this._MaPTN = value.MaPTN;
					}
					else
					{
						this._MaPTN = default(string);
					}
					this.SendPropertyChanged("PhongThiNghiem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThietBi_PhanThietBi", Storage="_ThietBi", ThisKey="MaTB", OtherKey="MaTB", IsForeignKey=true)]
		public ThietBi ThietBi
		{
			get
			{
				return this._ThietBi.Entity;
			}
			set
			{
				ThietBi previousValue = this._ThietBi.Entity;
				if (((previousValue != value) 
							|| (this._ThietBi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThietBi.Entity = null;
						previousValue.PhanThietBis.Remove(this);
					}
					this._ThietBi.Entity = value;
					if ((value != null))
					{
						value.PhanThietBis.Add(this);
						this._MaTB = value.MaTB;
					}
					else
					{
						this._MaTB = default(string);
					}
					this.SendPropertyChanged("ThietBi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khoa")]
	public partial class Khoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhoa;
		
		private string _TenKhoa;
		
		private string _DiaChiKhoa;
		
		private EntitySet<SinhVien> _SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnTenKhoaChanging(string value);
    partial void OnTenKhoaChanged();
    partial void OnDiaChiKhoaChanging(string value);
    partial void OnDiaChiKhoaChanged();
    #endregion
		
		public Khoa()
		{
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoa", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenKhoa
		{
			get
			{
				return this._TenKhoa;
			}
			set
			{
				if ((this._TenKhoa != value))
				{
					this.OnTenKhoaChanging(value);
					this.SendPropertyChanging();
					this._TenKhoa = value;
					this.SendPropertyChanged("TenKhoa");
					this.OnTenKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiKhoa", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChiKhoa
		{
			get
			{
				return this._DiaChiKhoa;
			}
			set
			{
				if ((this._DiaChiKhoa != value))
				{
					this.OnDiaChiKhoaChanging(value);
					this.SendPropertyChanging();
					this._DiaChiKhoa = value;
					this.SendPropertyChanged("DiaChiKhoa");
					this.OnDiaChiKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_SinhVien", Storage="_SinhViens", ThisKey="MaKhoa", OtherKey="MaKhoa")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.Khoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeAn")]
	public partial class DeAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDA;
		
		private string _TenDA;
		
		private string _MaGVHD;
		
		private string _MaNhom;
		
		private EntityRef<NhomSV> _NhomSV;
		
		private EntityRef<GiaoVienHD> _GiaoVienHD;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDAChanging(string value);
    partial void OnMaDAChanged();
    partial void OnTenDAChanging(string value);
    partial void OnTenDAChanged();
    partial void OnMaGVHDChanging(string value);
    partial void OnMaGVHDChanged();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    #endregion
		
		public DeAn()
		{
			this._NhomSV = default(EntityRef<NhomSV>);
			this._GiaoVienHD = default(EntityRef<GiaoVienHD>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDA", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDA
		{
			get
			{
				return this._MaDA;
			}
			set
			{
				if ((this._MaDA != value))
				{
					this.OnMaDAChanging(value);
					this.SendPropertyChanging();
					this._MaDA = value;
					this.SendPropertyChanged("MaDA");
					this.OnMaDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDA", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string TenDA
		{
			get
			{
				return this._TenDA;
			}
			set
			{
				if ((this._TenDA != value))
				{
					this.OnTenDAChanging(value);
					this.SendPropertyChanging();
					this._TenDA = value;
					this.SendPropertyChanged("TenDA");
					this.OnTenDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGVHD", DbType="NChar(10)")]
		public string MaGVHD
		{
			get
			{
				return this._MaGVHD;
			}
			set
			{
				if ((this._MaGVHD != value))
				{
					if (this._GiaoVienHD.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGVHDChanging(value);
					this.SendPropertyChanging();
					this._MaGVHD = value;
					this.SendPropertyChanged("MaGVHD");
					this.OnMaGVHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="NChar(10)")]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._NhomSV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSV_DeAn", Storage="_NhomSV", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public NhomSV NhomSV
		{
			get
			{
				return this._NhomSV.Entity;
			}
			set
			{
				NhomSV previousValue = this._NhomSV.Entity;
				if (((previousValue != value) 
							|| (this._NhomSV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomSV.Entity = null;
						previousValue.DeAns.Remove(this);
					}
					this._NhomSV.Entity = value;
					if ((value != null))
					{
						value.DeAns.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("NhomSV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVienHD_DeAn", Storage="_GiaoVienHD", ThisKey="MaGVHD", OtherKey="MaGVHD", IsForeignKey=true)]
		public GiaoVienHD GiaoVienHD
		{
			get
			{
				return this._GiaoVienHD.Entity;
			}
			set
			{
				GiaoVienHD previousValue = this._GiaoVienHD.Entity;
				if (((previousValue != value) 
							|| (this._GiaoVienHD.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiaoVienHD.Entity = null;
						previousValue.DeAns.Remove(this);
					}
					this._GiaoVienHD.Entity = value;
					if ((value != null))
					{
						value.DeAns.Add(this);
						this._MaGVHD = value.MaGVHD;
					}
					else
					{
						this._MaGVHD = default(string);
					}
					this.SendPropertyChanged("GiaoVienHD");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKyDC")]
	public partial class DangKyDC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _MaDC;
		
		private System.Nullable<int> _SoLuongDC_DK;
		
		private EntityRef<NhomSV> _NhomSV;
		
		private EntityRef<DungCu> _DungCu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnMaDCChanging(string value);
    partial void OnMaDCChanged();
    partial void OnSoLuongDC_DKChanging(System.Nullable<int> value);
    partial void OnSoLuongDC_DKChanged();
    #endregion
		
		public DangKyDC()
		{
			this._NhomSV = default(EntityRef<NhomSV>);
			this._DungCu = default(EntityRef<DungCu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._NhomSV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDC", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDC
		{
			get
			{
				return this._MaDC;
			}
			set
			{
				if ((this._MaDC != value))
				{
					if (this._DungCu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDCChanging(value);
					this.SendPropertyChanging();
					this._MaDC = value;
					this.SendPropertyChanged("MaDC");
					this.OnMaDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDC_DK", DbType="Int")]
		public System.Nullable<int> SoLuongDC_DK
		{
			get
			{
				return this._SoLuongDC_DK;
			}
			set
			{
				if ((this._SoLuongDC_DK != value))
				{
					this.OnSoLuongDC_DKChanging(value);
					this.SendPropertyChanging();
					this._SoLuongDC_DK = value;
					this.SendPropertyChanged("SoLuongDC_DK");
					this.OnSoLuongDC_DKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSV_DangKyDC", Storage="_NhomSV", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public NhomSV NhomSV
		{
			get
			{
				return this._NhomSV.Entity;
			}
			set
			{
				NhomSV previousValue = this._NhomSV.Entity;
				if (((previousValue != value) 
							|| (this._NhomSV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomSV.Entity = null;
						previousValue.DangKyDCs.Remove(this);
					}
					this._NhomSV.Entity = value;
					if ((value != null))
					{
						value.DangKyDCs.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("NhomSV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DungCu_DangKyDC", Storage="_DungCu", ThisKey="MaDC", OtherKey="MaDC", IsForeignKey=true)]
		public DungCu DungCu
		{
			get
			{
				return this._DungCu.Entity;
			}
			set
			{
				DungCu previousValue = this._DungCu.Entity;
				if (((previousValue != value) 
							|| (this._DungCu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DungCu.Entity = null;
						previousValue.DangKyDCs.Remove(this);
					}
					this._DungCu.Entity = value;
					if ((value != null))
					{
						value.DangKyDCs.Add(this);
						this._MaDC = value.MaDC;
					}
					else
					{
						this._MaDC = default(string);
					}
					this.SendPropertyChanged("DungCu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKyHC")]
	public partial class DangKyHC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _MaHC;
		
		private System.Nullable<int> _SoLuongHC_DK;
		
		private EntityRef<NhomSV> _NhomSV;
		
		private EntityRef<HoaChat> _HoaChat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnMaHCChanging(string value);
    partial void OnMaHCChanged();
    partial void OnSoLuongHC_DKChanging(System.Nullable<int> value);
    partial void OnSoLuongHC_DKChanged();
    #endregion
		
		public DangKyHC()
		{
			this._NhomSV = default(EntityRef<NhomSV>);
			this._HoaChat = default(EntityRef<HoaChat>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._NhomSV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHC", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHC
		{
			get
			{
				return this._MaHC;
			}
			set
			{
				if ((this._MaHC != value))
				{
					if (this._HoaChat.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHCChanging(value);
					this.SendPropertyChanging();
					this._MaHC = value;
					this.SendPropertyChanged("MaHC");
					this.OnMaHCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongHC_DK", DbType="Int")]
		public System.Nullable<int> SoLuongHC_DK
		{
			get
			{
				return this._SoLuongHC_DK;
			}
			set
			{
				if ((this._SoLuongHC_DK != value))
				{
					this.OnSoLuongHC_DKChanging(value);
					this.SendPropertyChanging();
					this._SoLuongHC_DK = value;
					this.SendPropertyChanged("SoLuongHC_DK");
					this.OnSoLuongHC_DKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSV_DangKyHC", Storage="_NhomSV", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public NhomSV NhomSV
		{
			get
			{
				return this._NhomSV.Entity;
			}
			set
			{
				NhomSV previousValue = this._NhomSV.Entity;
				if (((previousValue != value) 
							|| (this._NhomSV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomSV.Entity = null;
						previousValue.DangKyHCs.Remove(this);
					}
					this._NhomSV.Entity = value;
					if ((value != null))
					{
						value.DangKyHCs.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("NhomSV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaChat_DangKyHC", Storage="_HoaChat", ThisKey="MaHC", OtherKey="MaHC", IsForeignKey=true)]
		public HoaChat HoaChat
		{
			get
			{
				return this._HoaChat.Entity;
			}
			set
			{
				HoaChat previousValue = this._HoaChat.Entity;
				if (((previousValue != value) 
							|| (this._HoaChat.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaChat.Entity = null;
						previousValue.DangKyHCs.Remove(this);
					}
					this._HoaChat.Entity = value;
					if ((value != null))
					{
						value.DangKyHCs.Add(this);
						this._MaHC = value.MaHC;
					}
					else
					{
						this._MaHC = default(string);
					}
					this.SendPropertyChanged("HoaChat");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKyTapSDTB")]
	public partial class DangKyTapSDTB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPTN;
		
		private string _MaNhom;
		
		private System.DateTime _NgayTN;
		
		private System.Nullable<System.TimeSpan> _ThoiGianBD;
		
		private System.Nullable<System.TimeSpan> _ThoiGianKT;
		
		private EntityRef<NhomSV> _NhomSV;
		
		private EntityRef<PhongThiNghiem> _PhongThiNghiem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPTNChanging(string value);
    partial void OnMaPTNChanged();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnNgayTNChanging(System.DateTime value);
    partial void OnNgayTNChanged();
    partial void OnThoiGianBDChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoiGianBDChanged();
    partial void OnThoiGianKTChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoiGianKTChanged();
    #endregion
		
		public DangKyTapSDTB()
		{
			this._NhomSV = default(EntityRef<NhomSV>);
			this._PhongThiNghiem = default(EntityRef<PhongThiNghiem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPTN", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPTN
		{
			get
			{
				return this._MaPTN;
			}
			set
			{
				if ((this._MaPTN != value))
				{
					if (this._PhongThiNghiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPTNChanging(value);
					this.SendPropertyChanging();
					this._MaPTN = value;
					this.SendPropertyChanged("MaPTN");
					this.OnMaPTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._NhomSV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTN", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NgayTN
		{
			get
			{
				return this._NgayTN;
			}
			set
			{
				if ((this._NgayTN != value))
				{
					this.OnNgayTNChanging(value);
					this.SendPropertyChanging();
					this._NgayTN = value;
					this.SendPropertyChanged("NgayTN");
					this.OnNgayTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBD", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThoiGianBD
		{
			get
			{
				return this._ThoiGianBD;
			}
			set
			{
				if ((this._ThoiGianBD != value))
				{
					this.OnThoiGianBDChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBD = value;
					this.SendPropertyChanged("ThoiGianBD");
					this.OnThoiGianBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKT", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThoiGianKT
		{
			get
			{
				return this._ThoiGianKT;
			}
			set
			{
				if ((this._ThoiGianKT != value))
				{
					this.OnThoiGianKTChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKT = value;
					this.SendPropertyChanged("ThoiGianKT");
					this.OnThoiGianKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSV_DangKyTapSDTB", Storage="_NhomSV", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public NhomSV NhomSV
		{
			get
			{
				return this._NhomSV.Entity;
			}
			set
			{
				NhomSV previousValue = this._NhomSV.Entity;
				if (((previousValue != value) 
							|| (this._NhomSV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomSV.Entity = null;
						previousValue.DangKyTapSDTBs.Remove(this);
					}
					this._NhomSV.Entity = value;
					if ((value != null))
					{
						value.DangKyTapSDTBs.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("NhomSV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongThiNghiem_DangKyTapSDTB", Storage="_PhongThiNghiem", ThisKey="MaPTN", OtherKey="MaPTN", IsForeignKey=true)]
		public PhongThiNghiem PhongThiNghiem
		{
			get
			{
				return this._PhongThiNghiem.Entity;
			}
			set
			{
				PhongThiNghiem previousValue = this._PhongThiNghiem.Entity;
				if (((previousValue != value) 
							|| (this._PhongThiNghiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongThiNghiem.Entity = null;
						previousValue.DangKyTapSDTBs.Remove(this);
					}
					this._PhongThiNghiem.Entity = value;
					if ((value != null))
					{
						value.DangKyTapSDTBs.Add(this);
						this._MaPTN = value.MaPTN;
					}
					else
					{
						this._MaPTN = default(string);
					}
					this.SendPropertyChanged("PhongThiNghiem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKyTN")]
	public partial class DangKyTN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPTN;
		
		private string _MaNhom;
		
		private System.DateTime _NgayTN;
		
		private System.Nullable<System.TimeSpan> _ThoiGianBD;
		
		private System.Nullable<System.TimeSpan> _ThoiGianKT;
		
		private EntityRef<NhomSV> _NhomSV;
		
		private EntityRef<PhongThiNghiem> _PhongThiNghiem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPTNChanging(string value);
    partial void OnMaPTNChanged();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnNgayTNChanging(System.DateTime value);
    partial void OnNgayTNChanged();
    partial void OnThoiGianBDChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoiGianBDChanged();
    partial void OnThoiGianKTChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoiGianKTChanged();
    #endregion
		
		public DangKyTN()
		{
			this._NhomSV = default(EntityRef<NhomSV>);
			this._PhongThiNghiem = default(EntityRef<PhongThiNghiem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPTN", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPTN
		{
			get
			{
				return this._MaPTN;
			}
			set
			{
				if ((this._MaPTN != value))
				{
					if (this._PhongThiNghiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPTNChanging(value);
					this.SendPropertyChanging();
					this._MaPTN = value;
					this.SendPropertyChanged("MaPTN");
					this.OnMaPTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._NhomSV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTN", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NgayTN
		{
			get
			{
				return this._NgayTN;
			}
			set
			{
				if ((this._NgayTN != value))
				{
					this.OnNgayTNChanging(value);
					this.SendPropertyChanging();
					this._NgayTN = value;
					this.SendPropertyChanged("NgayTN");
					this.OnNgayTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBD", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThoiGianBD
		{
			get
			{
				return this._ThoiGianBD;
			}
			set
			{
				if ((this._ThoiGianBD != value))
				{
					this.OnThoiGianBDChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBD = value;
					this.SendPropertyChanged("ThoiGianBD");
					this.OnThoiGianBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKT", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThoiGianKT
		{
			get
			{
				return this._ThoiGianKT;
			}
			set
			{
				if ((this._ThoiGianKT != value))
				{
					this.OnThoiGianKTChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKT = value;
					this.SendPropertyChanged("ThoiGianKT");
					this.OnThoiGianKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSV_DangKyTN", Storage="_NhomSV", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public NhomSV NhomSV
		{
			get
			{
				return this._NhomSV.Entity;
			}
			set
			{
				NhomSV previousValue = this._NhomSV.Entity;
				if (((previousValue != value) 
							|| (this._NhomSV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomSV.Entity = null;
						previousValue.DangKyTNs.Remove(this);
					}
					this._NhomSV.Entity = value;
					if ((value != null))
					{
						value.DangKyTNs.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("NhomSV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongThiNghiem_DangKyTN", Storage="_PhongThiNghiem", ThisKey="MaPTN", OtherKey="MaPTN", IsForeignKey=true)]
		public PhongThiNghiem PhongThiNghiem
		{
			get
			{
				return this._PhongThiNghiem.Entity;
			}
			set
			{
				PhongThiNghiem previousValue = this._PhongThiNghiem.Entity;
				if (((previousValue != value) 
							|| (this._PhongThiNghiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongThiNghiem.Entity = null;
						previousValue.DangKyTNs.Remove(this);
					}
					this._PhongThiNghiem.Entity = value;
					if ((value != null))
					{
						value.DangKyTNs.Add(this);
						this._MaPTN = value.MaPTN;
					}
					else
					{
						this._MaPTN = default(string);
					}
					this.SendPropertyChanged("PhongThiNghiem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DungCu")]
	public partial class DungCu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDC;
		
		private string _TenDC;
		
		private string _QuyCach_DC;
		
		private string _DonViTinh_DC;
		
		private System.Nullable<int> _SoLuong_DC;
		
		private EntitySet<DangKyDC> _DangKyDCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDCChanging(string value);
    partial void OnMaDCChanged();
    partial void OnTenDCChanging(string value);
    partial void OnTenDCChanged();
    partial void OnQuyCach_DCChanging(string value);
    partial void OnQuyCach_DCChanged();
    partial void OnDonViTinh_DCChanging(string value);
    partial void OnDonViTinh_DCChanged();
    partial void OnSoLuong_DCChanging(System.Nullable<int> value);
    partial void OnSoLuong_DCChanged();
    #endregion
		
		public DungCu()
		{
			this._DangKyDCs = new EntitySet<DangKyDC>(new Action<DangKyDC>(this.attach_DangKyDCs), new Action<DangKyDC>(this.detach_DangKyDCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDC", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDC
		{
			get
			{
				return this._MaDC;
			}
			set
			{
				if ((this._MaDC != value))
				{
					this.OnMaDCChanging(value);
					this.SendPropertyChanging();
					this._MaDC = value;
					this.SendPropertyChanged("MaDC");
					this.OnMaDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDC", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenDC
		{
			get
			{
				return this._TenDC;
			}
			set
			{
				if ((this._TenDC != value))
				{
					this.OnTenDCChanging(value);
					this.SendPropertyChanging();
					this._TenDC = value;
					this.SendPropertyChanged("TenDC");
					this.OnTenDCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyCach_DC", DbType="NVarChar(20)")]
		public string QuyCach_DC
		{
			get
			{
				return this._QuyCach_DC;
			}
			set
			{
				if ((this._QuyCach_DC != value))
				{
					this.OnQuyCach_DCChanging(value);
					this.SendPropertyChanging();
					this._QuyCach_DC = value;
					this.SendPropertyChanged("QuyCach_DC");
					this.OnQuyCach_DCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh_DC", DbType="NVarChar(20)")]
		public string DonViTinh_DC
		{
			get
			{
				return this._DonViTinh_DC;
			}
			set
			{
				if ((this._DonViTinh_DC != value))
				{
					this.OnDonViTinh_DCChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh_DC = value;
					this.SendPropertyChanged("DonViTinh_DC");
					this.OnDonViTinh_DCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong_DC", DbType="Int")]
		public System.Nullable<int> SoLuong_DC
		{
			get
			{
				return this._SoLuong_DC;
			}
			set
			{
				if ((this._SoLuong_DC != value))
				{
					this.OnSoLuong_DCChanging(value);
					this.SendPropertyChanging();
					this._SoLuong_DC = value;
					this.SendPropertyChanged("SoLuong_DC");
					this.OnSoLuong_DCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DungCu_DangKyDC", Storage="_DangKyDCs", ThisKey="MaDC", OtherKey="MaDC")]
		public EntitySet<DangKyDC> DangKyDCs
		{
			get
			{
				return this._DangKyDCs;
			}
			set
			{
				this._DangKyDCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKyDCs(DangKyDC entity)
		{
			this.SendPropertyChanging();
			entity.DungCu = this;
		}
		
		private void detach_DangKyDCs(DangKyDC entity)
		{
			this.SendPropertyChanging();
			entity.DungCu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaoVienHD")]
	public partial class GiaoVienHD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGVHD;
		
		private string _TenGVHD;
		
		private string _SDT_GVHD;
		
		private EntitySet<DeAn> _DeAns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGVHDChanging(string value);
    partial void OnMaGVHDChanged();
    partial void OnTenGVHDChanging(string value);
    partial void OnTenGVHDChanged();
    partial void OnSDT_GVHDChanging(string value);
    partial void OnSDT_GVHDChanged();
    #endregion
		
		public GiaoVienHD()
		{
			this._DeAns = new EntitySet<DeAn>(new Action<DeAn>(this.attach_DeAns), new Action<DeAn>(this.detach_DeAns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGVHD", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGVHD
		{
			get
			{
				return this._MaGVHD;
			}
			set
			{
				if ((this._MaGVHD != value))
				{
					this.OnMaGVHDChanging(value);
					this.SendPropertyChanging();
					this._MaGVHD = value;
					this.SendPropertyChanged("MaGVHD");
					this.OnMaGVHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGVHD", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenGVHD
		{
			get
			{
				return this._TenGVHD;
			}
			set
			{
				if ((this._TenGVHD != value))
				{
					this.OnTenGVHDChanging(value);
					this.SendPropertyChanging();
					this._TenGVHD = value;
					this.SendPropertyChanged("TenGVHD");
					this.OnTenGVHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT_GVHD", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string SDT_GVHD
		{
			get
			{
				return this._SDT_GVHD;
			}
			set
			{
				if ((this._SDT_GVHD != value))
				{
					this.OnSDT_GVHDChanging(value);
					this.SendPropertyChanging();
					this._SDT_GVHD = value;
					this.SendPropertyChanged("SDT_GVHD");
					this.OnSDT_GVHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVienHD_DeAn", Storage="_DeAns", ThisKey="MaGVHD", OtherKey="MaGVHD")]
		public EntitySet<DeAn> DeAns
		{
			get
			{
				return this._DeAns;
			}
			set
			{
				this._DeAns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeAns(DeAn entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVienHD = this;
		}
		
		private void detach_DeAns(DeAn entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVienHD = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaoVienQLPTN")]
	public partial class GiaoVienQLPTN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGVQLPTN;
		
		private string _TenGVQLPTN;
		
		private string _SDT_GVQLPTN;
		
		private EntitySet<PhongThiNghiem> _PhongThiNghiems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGVQLPTNChanging(string value);
    partial void OnMaGVQLPTNChanged();
    partial void OnTenGVQLPTNChanging(string value);
    partial void OnTenGVQLPTNChanged();
    partial void OnSDT_GVQLPTNChanging(string value);
    partial void OnSDT_GVQLPTNChanged();
    #endregion
		
		public GiaoVienQLPTN()
		{
			this._PhongThiNghiems = new EntitySet<PhongThiNghiem>(new Action<PhongThiNghiem>(this.attach_PhongThiNghiems), new Action<PhongThiNghiem>(this.detach_PhongThiNghiems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGVQLPTN", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGVQLPTN
		{
			get
			{
				return this._MaGVQLPTN;
			}
			set
			{
				if ((this._MaGVQLPTN != value))
				{
					this.OnMaGVQLPTNChanging(value);
					this.SendPropertyChanging();
					this._MaGVQLPTN = value;
					this.SendPropertyChanged("MaGVQLPTN");
					this.OnMaGVQLPTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGVQLPTN", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenGVQLPTN
		{
			get
			{
				return this._TenGVQLPTN;
			}
			set
			{
				if ((this._TenGVQLPTN != value))
				{
					this.OnTenGVQLPTNChanging(value);
					this.SendPropertyChanging();
					this._TenGVQLPTN = value;
					this.SendPropertyChanged("TenGVQLPTN");
					this.OnTenGVQLPTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT_GVQLPTN", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string SDT_GVQLPTN
		{
			get
			{
				return this._SDT_GVQLPTN;
			}
			set
			{
				if ((this._SDT_GVQLPTN != value))
				{
					this.OnSDT_GVQLPTNChanging(value);
					this.SendPropertyChanging();
					this._SDT_GVQLPTN = value;
					this.SendPropertyChanged("SDT_GVQLPTN");
					this.OnSDT_GVQLPTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVienQLPTN_PhongThiNghiem", Storage="_PhongThiNghiems", ThisKey="MaGVQLPTN", OtherKey="MaGVQLPTN")]
		public EntitySet<PhongThiNghiem> PhongThiNghiems
		{
			get
			{
				return this._PhongThiNghiems;
			}
			set
			{
				this._PhongThiNghiems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhongThiNghiems(PhongThiNghiem entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVienQLPTN = this;
		}
		
		private void detach_PhongThiNghiems(PhongThiNghiem entity)
		{
			this.SendPropertyChanging();
			entity.GiaoVienQLPTN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaChat")]
	public partial class HoaChat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHC;
		
		private string _TenHC;
		
		private string _QuyCach_HC;
		
		private string _DonViTinh_HC;
		
		private System.Nullable<int> _SoLuong_HC;
		
		private EntitySet<DangKyHC> _DangKyHCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHCChanging(string value);
    partial void OnMaHCChanged();
    partial void OnTenHCChanging(string value);
    partial void OnTenHCChanged();
    partial void OnQuyCach_HCChanging(string value);
    partial void OnQuyCach_HCChanged();
    partial void OnDonViTinh_HCChanging(string value);
    partial void OnDonViTinh_HCChanged();
    partial void OnSoLuong_HCChanging(System.Nullable<int> value);
    partial void OnSoLuong_HCChanged();
    #endregion
		
		public HoaChat()
		{
			this._DangKyHCs = new EntitySet<DangKyHC>(new Action<DangKyHC>(this.attach_DangKyHCs), new Action<DangKyHC>(this.detach_DangKyHCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHC", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHC
		{
			get
			{
				return this._MaHC;
			}
			set
			{
				if ((this._MaHC != value))
				{
					this.OnMaHCChanging(value);
					this.SendPropertyChanging();
					this._MaHC = value;
					this.SendPropertyChanged("MaHC");
					this.OnMaHCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHC", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenHC
		{
			get
			{
				return this._TenHC;
			}
			set
			{
				if ((this._TenHC != value))
				{
					this.OnTenHCChanging(value);
					this.SendPropertyChanging();
					this._TenHC = value;
					this.SendPropertyChanged("TenHC");
					this.OnTenHCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyCach_HC", DbType="NVarChar(20)")]
		public string QuyCach_HC
		{
			get
			{
				return this._QuyCach_HC;
			}
			set
			{
				if ((this._QuyCach_HC != value))
				{
					this.OnQuyCach_HCChanging(value);
					this.SendPropertyChanging();
					this._QuyCach_HC = value;
					this.SendPropertyChanged("QuyCach_HC");
					this.OnQuyCach_HCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh_HC", DbType="NVarChar(20)")]
		public string DonViTinh_HC
		{
			get
			{
				return this._DonViTinh_HC;
			}
			set
			{
				if ((this._DonViTinh_HC != value))
				{
					this.OnDonViTinh_HCChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh_HC = value;
					this.SendPropertyChanged("DonViTinh_HC");
					this.OnDonViTinh_HCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong_HC", DbType="Int")]
		public System.Nullable<int> SoLuong_HC
		{
			get
			{
				return this._SoLuong_HC;
			}
			set
			{
				if ((this._SoLuong_HC != value))
				{
					this.OnSoLuong_HCChanging(value);
					this.SendPropertyChanging();
					this._SoLuong_HC = value;
					this.SendPropertyChanged("SoLuong_HC");
					this.OnSoLuong_HCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaChat_DangKyHC", Storage="_DangKyHCs", ThisKey="MaHC", OtherKey="MaHC")]
		public EntitySet<DangKyHC> DangKyHCs
		{
			get
			{
				return this._DangKyHCs;
			}
			set
			{
				this._DangKyHCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKyHCs(DangKyHC entity)
		{
			this.SendPropertyChanging();
			entity.HoaChat = this;
		}
		
		private void detach_DangKyHCs(DangKyHC entity)
		{
			this.SendPropertyChanging();
			entity.HoaChat = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanThietBi_LT")]
	public partial class PhanThietBi_LT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _NgayPhan;
		
		private string _MaPTN;
		
		private string _MaTB;
		
		private System.Nullable<int> _SoLuongPhan_TB;
		
		private EntityRef<PhongThiNghiem> _PhongThiNghiem;
		
		private EntityRef<ThietBi> _ThietBi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNgayPhanChanging(System.DateTime value);
    partial void OnNgayPhanChanged();
    partial void OnMaPTNChanging(string value);
    partial void OnMaPTNChanged();
    partial void OnMaTBChanging(string value);
    partial void OnMaTBChanged();
    partial void OnSoLuongPhan_TBChanging(System.Nullable<int> value);
    partial void OnSoLuongPhan_TBChanged();
    #endregion
		
		public PhanThietBi_LT()
		{
			this._PhongThiNghiem = default(EntityRef<PhongThiNghiem>);
			this._ThietBi = default(EntityRef<ThietBi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayPhan", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NgayPhan
		{
			get
			{
				return this._NgayPhan;
			}
			set
			{
				if ((this._NgayPhan != value))
				{
					this.OnNgayPhanChanging(value);
					this.SendPropertyChanging();
					this._NgayPhan = value;
					this.SendPropertyChanged("NgayPhan");
					this.OnNgayPhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPTN", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPTN
		{
			get
			{
				return this._MaPTN;
			}
			set
			{
				if ((this._MaPTN != value))
				{
					if (this._PhongThiNghiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPTNChanging(value);
					this.SendPropertyChanging();
					this._MaPTN = value;
					this.SendPropertyChanged("MaPTN");
					this.OnMaPTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTB", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTB
		{
			get
			{
				return this._MaTB;
			}
			set
			{
				if ((this._MaTB != value))
				{
					if (this._ThietBi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTBChanging(value);
					this.SendPropertyChanging();
					this._MaTB = value;
					this.SendPropertyChanged("MaTB");
					this.OnMaTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongPhan_TB", DbType="Int")]
		public System.Nullable<int> SoLuongPhan_TB
		{
			get
			{
				return this._SoLuongPhan_TB;
			}
			set
			{
				if ((this._SoLuongPhan_TB != value))
				{
					this.OnSoLuongPhan_TBChanging(value);
					this.SendPropertyChanging();
					this._SoLuongPhan_TB = value;
					this.SendPropertyChanged("SoLuongPhan_TB");
					this.OnSoLuongPhan_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongThiNghiem_PhanThietBi_LT", Storage="_PhongThiNghiem", ThisKey="MaPTN", OtherKey="MaPTN", IsForeignKey=true)]
		public PhongThiNghiem PhongThiNghiem
		{
			get
			{
				return this._PhongThiNghiem.Entity;
			}
			set
			{
				PhongThiNghiem previousValue = this._PhongThiNghiem.Entity;
				if (((previousValue != value) 
							|| (this._PhongThiNghiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhongThiNghiem.Entity = null;
						previousValue.PhanThietBi_LTs.Remove(this);
					}
					this._PhongThiNghiem.Entity = value;
					if ((value != null))
					{
						value.PhanThietBi_LTs.Add(this);
						this._MaPTN = value.MaPTN;
					}
					else
					{
						this._MaPTN = default(string);
					}
					this.SendPropertyChanged("PhongThiNghiem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThietBi_PhanThietBi_LT", Storage="_ThietBi", ThisKey="MaTB", OtherKey="MaTB", IsForeignKey=true)]
		public ThietBi ThietBi
		{
			get
			{
				return this._ThietBi.Entity;
			}
			set
			{
				ThietBi previousValue = this._ThietBi.Entity;
				if (((previousValue != value) 
							|| (this._ThietBi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThietBi.Entity = null;
						previousValue.PhanThietBi_LTs.Remove(this);
					}
					this._ThietBi.Entity = value;
					if ((value != null))
					{
						value.PhanThietBi_LTs.Add(this);
						this._MaTB = value.MaTB;
					}
					else
					{
						this._MaTB = default(string);
					}
					this.SendPropertyChanged("ThietBi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhongThiNghiem")]
	public partial class PhongThiNghiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPTN;
		
		private string _TenPTN;
		
		private string _DiaChiPTN;
		
		private string _MaGVQLPTN;
		
		private EntitySet<PhanThietBi> _PhanThietBis;
		
		private EntitySet<DangKyTapSDTB> _DangKyTapSDTBs;
		
		private EntitySet<DangKyTN> _DangKyTNs;
		
		private EntitySet<PhanThietBi_LT> _PhanThietBi_LTs;
		
		private EntityRef<GiaoVienQLPTN> _GiaoVienQLPTN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPTNChanging(string value);
    partial void OnMaPTNChanged();
    partial void OnTenPTNChanging(string value);
    partial void OnTenPTNChanged();
    partial void OnDiaChiPTNChanging(string value);
    partial void OnDiaChiPTNChanged();
    partial void OnMaGVQLPTNChanging(string value);
    partial void OnMaGVQLPTNChanged();
    #endregion
		
		public PhongThiNghiem()
		{
			this._PhanThietBis = new EntitySet<PhanThietBi>(new Action<PhanThietBi>(this.attach_PhanThietBis), new Action<PhanThietBi>(this.detach_PhanThietBis));
			this._DangKyTapSDTBs = new EntitySet<DangKyTapSDTB>(new Action<DangKyTapSDTB>(this.attach_DangKyTapSDTBs), new Action<DangKyTapSDTB>(this.detach_DangKyTapSDTBs));
			this._DangKyTNs = new EntitySet<DangKyTN>(new Action<DangKyTN>(this.attach_DangKyTNs), new Action<DangKyTN>(this.detach_DangKyTNs));
			this._PhanThietBi_LTs = new EntitySet<PhanThietBi_LT>(new Action<PhanThietBi_LT>(this.attach_PhanThietBi_LTs), new Action<PhanThietBi_LT>(this.detach_PhanThietBi_LTs));
			this._GiaoVienQLPTN = default(EntityRef<GiaoVienQLPTN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPTN", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPTN
		{
			get
			{
				return this._MaPTN;
			}
			set
			{
				if ((this._MaPTN != value))
				{
					this.OnMaPTNChanging(value);
					this.SendPropertyChanging();
					this._MaPTN = value;
					this.SendPropertyChanged("MaPTN");
					this.OnMaPTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPTN", DbType="NVarChar(20)")]
		public string TenPTN
		{
			get
			{
				return this._TenPTN;
			}
			set
			{
				if ((this._TenPTN != value))
				{
					this.OnTenPTNChanging(value);
					this.SendPropertyChanging();
					this._TenPTN = value;
					this.SendPropertyChanged("TenPTN");
					this.OnTenPTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiPTN", DbType="NVarChar(50)")]
		public string DiaChiPTN
		{
			get
			{
				return this._DiaChiPTN;
			}
			set
			{
				if ((this._DiaChiPTN != value))
				{
					this.OnDiaChiPTNChanging(value);
					this.SendPropertyChanging();
					this._DiaChiPTN = value;
					this.SendPropertyChanged("DiaChiPTN");
					this.OnDiaChiPTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGVQLPTN", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaGVQLPTN
		{
			get
			{
				return this._MaGVQLPTN;
			}
			set
			{
				if ((this._MaGVQLPTN != value))
				{
					if (this._GiaoVienQLPTN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGVQLPTNChanging(value);
					this.SendPropertyChanging();
					this._MaGVQLPTN = value;
					this.SendPropertyChanged("MaGVQLPTN");
					this.OnMaGVQLPTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongThiNghiem_PhanThietBi", Storage="_PhanThietBis", ThisKey="MaPTN", OtherKey="MaPTN")]
		public EntitySet<PhanThietBi> PhanThietBis
		{
			get
			{
				return this._PhanThietBis;
			}
			set
			{
				this._PhanThietBis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongThiNghiem_DangKyTapSDTB", Storage="_DangKyTapSDTBs", ThisKey="MaPTN", OtherKey="MaPTN")]
		public EntitySet<DangKyTapSDTB> DangKyTapSDTBs
		{
			get
			{
				return this._DangKyTapSDTBs;
			}
			set
			{
				this._DangKyTapSDTBs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongThiNghiem_DangKyTN", Storage="_DangKyTNs", ThisKey="MaPTN", OtherKey="MaPTN")]
		public EntitySet<DangKyTN> DangKyTNs
		{
			get
			{
				return this._DangKyTNs;
			}
			set
			{
				this._DangKyTNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhongThiNghiem_PhanThietBi_LT", Storage="_PhanThietBi_LTs", ThisKey="MaPTN", OtherKey="MaPTN")]
		public EntitySet<PhanThietBi_LT> PhanThietBi_LTs
		{
			get
			{
				return this._PhanThietBi_LTs;
			}
			set
			{
				this._PhanThietBi_LTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GiaoVienQLPTN_PhongThiNghiem", Storage="_GiaoVienQLPTN", ThisKey="MaGVQLPTN", OtherKey="MaGVQLPTN", IsForeignKey=true)]
		public GiaoVienQLPTN GiaoVienQLPTN
		{
			get
			{
				return this._GiaoVienQLPTN.Entity;
			}
			set
			{
				GiaoVienQLPTN previousValue = this._GiaoVienQLPTN.Entity;
				if (((previousValue != value) 
							|| (this._GiaoVienQLPTN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GiaoVienQLPTN.Entity = null;
						previousValue.PhongThiNghiems.Remove(this);
					}
					this._GiaoVienQLPTN.Entity = value;
					if ((value != null))
					{
						value.PhongThiNghiems.Add(this);
						this._MaGVQLPTN = value.MaGVQLPTN;
					}
					else
					{
						this._MaGVQLPTN = default(string);
					}
					this.SendPropertyChanged("GiaoVienQLPTN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanThietBis(PhanThietBi entity)
		{
			this.SendPropertyChanging();
			entity.PhongThiNghiem = this;
		}
		
		private void detach_PhanThietBis(PhanThietBi entity)
		{
			this.SendPropertyChanging();
			entity.PhongThiNghiem = null;
		}
		
		private void attach_DangKyTapSDTBs(DangKyTapSDTB entity)
		{
			this.SendPropertyChanging();
			entity.PhongThiNghiem = this;
		}
		
		private void detach_DangKyTapSDTBs(DangKyTapSDTB entity)
		{
			this.SendPropertyChanging();
			entity.PhongThiNghiem = null;
		}
		
		private void attach_DangKyTNs(DangKyTN entity)
		{
			this.SendPropertyChanging();
			entity.PhongThiNghiem = this;
		}
		
		private void detach_DangKyTNs(DangKyTN entity)
		{
			this.SendPropertyChanging();
			entity.PhongThiNghiem = null;
		}
		
		private void attach_PhanThietBi_LTs(PhanThietBi_LT entity)
		{
			this.SendPropertyChanging();
			entity.PhongThiNghiem = this;
		}
		
		private void detach_PhanThietBi_LTs(PhanThietBi_LT entity)
		{
			this.SendPropertyChanging();
			entity.PhongThiNghiem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _TenSV;
		
		private string _MaKhoa;
		
		private string _Nganh;
		
		private string _Lop;
		
		private System.Nullable<int> _HocKy;
		
		private int _NamHoc;
		
		private string _MaNhom;
		
		private EntityRef<Khoa> _Khoa;
		
		private EntityRef<NhomSV> _NhomSV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnTenSVChanging(string value);
    partial void OnTenSVChanged();
    partial void OnMaKhoaChanging(string value);
    partial void OnMaKhoaChanged();
    partial void OnNganhChanging(string value);
    partial void OnNganhChanged();
    partial void OnLopChanging(string value);
    partial void OnLopChanged();
    partial void OnHocKyChanging(System.Nullable<int> value);
    partial void OnHocKyChanged();
    partial void OnNamHocChanging(int value);
    partial void OnNamHocChanged();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    #endregion
		
		public SinhVien()
		{
			this._Khoa = default(EntityRef<Khoa>);
			this._NhomSV = default(EntityRef<NhomSV>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSV", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TenSV
		{
			get
			{
				return this._TenSV;
			}
			set
			{
				if ((this._TenSV != value))
				{
					this.OnTenSVChanging(value);
					this.SendPropertyChanging();
					this._TenSV = value;
					this.SendPropertyChanged("TenSV");
					this.OnTenSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoa", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaKhoa
		{
			get
			{
				return this._MaKhoa;
			}
			set
			{
				if ((this._MaKhoa != value))
				{
					if (this._Khoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaChanging(value);
					this.SendPropertyChanging();
					this._MaKhoa = value;
					this.SendPropertyChanged("MaKhoa");
					this.OnMaKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nganh", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Nganh
		{
			get
			{
				return this._Nganh;
			}
			set
			{
				if ((this._Nganh != value))
				{
					this.OnNganhChanging(value);
					this.SendPropertyChanging();
					this._Nganh = value;
					this.SendPropertyChanged("Nganh");
					this.OnNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Lop
		{
			get
			{
				return this._Lop;
			}
			set
			{
				if ((this._Lop != value))
				{
					this.OnLopChanging(value);
					this.SendPropertyChanging();
					this._Lop = value;
					this.SendPropertyChanged("Lop");
					this.OnLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HocKy", DbType="Int")]
		public System.Nullable<int> HocKy
		{
			get
			{
				return this._HocKy;
			}
			set
			{
				if ((this._HocKy != value))
				{
					this.OnHocKyChanging(value);
					this.SendPropertyChanging();
					this._HocKy = value;
					this.SendPropertyChanged("HocKy");
					this.OnHocKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamHoc", DbType="Int NOT NULL")]
		public int NamHoc
		{
			get
			{
				return this._NamHoc;
			}
			set
			{
				if ((this._NamHoc != value))
				{
					this.OnNamHocChanging(value);
					this.SendPropertyChanging();
					this._NamHoc = value;
					this.SendPropertyChanged("NamHoc");
					this.OnNamHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="NChar(10)")]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._NhomSV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khoa_SinhVien", Storage="_Khoa", ThisKey="MaKhoa", OtherKey="MaKhoa", IsForeignKey=true)]
		public Khoa Khoa
		{
			get
			{
				return this._Khoa.Entity;
			}
			set
			{
				Khoa previousValue = this._Khoa.Entity;
				if (((previousValue != value) 
							|| (this._Khoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khoa.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._Khoa.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._MaKhoa = value.MaKhoa;
					}
					else
					{
						this._MaKhoa = default(string);
					}
					this.SendPropertyChanged("Khoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomSV_SinhVien", Storage="_NhomSV", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public NhomSV NhomSV
		{
			get
			{
				return this._NhomSV.Entity;
			}
			set
			{
				NhomSV previousValue = this._NhomSV.Entity;
				if (((previousValue != value) 
							|| (this._NhomSV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomSV.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._NhomSV.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("NhomSV");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThietBi")]
	public partial class ThietBi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTB;
		
		private string _TenTB;
		
		private System.Nullable<int> _SoLuong_TB;
		
		private EntitySet<PhanThietBi> _PhanThietBis;
		
		private EntitySet<PhanThietBi_LT> _PhanThietBi_LTs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTBChanging(string value);
    partial void OnMaTBChanged();
    partial void OnTenTBChanging(string value);
    partial void OnTenTBChanged();
    partial void OnSoLuong_TBChanging(System.Nullable<int> value);
    partial void OnSoLuong_TBChanged();
    #endregion
		
		public ThietBi()
		{
			this._PhanThietBis = new EntitySet<PhanThietBi>(new Action<PhanThietBi>(this.attach_PhanThietBis), new Action<PhanThietBi>(this.detach_PhanThietBis));
			this._PhanThietBi_LTs = new EntitySet<PhanThietBi_LT>(new Action<PhanThietBi_LT>(this.attach_PhanThietBi_LTs), new Action<PhanThietBi_LT>(this.detach_PhanThietBi_LTs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTB", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTB
		{
			get
			{
				return this._MaTB;
			}
			set
			{
				if ((this._MaTB != value))
				{
					this.OnMaTBChanging(value);
					this.SendPropertyChanging();
					this._MaTB = value;
					this.SendPropertyChanged("MaTB");
					this.OnMaTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTB", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenTB
		{
			get
			{
				return this._TenTB;
			}
			set
			{
				if ((this._TenTB != value))
				{
					this.OnTenTBChanging(value);
					this.SendPropertyChanging();
					this._TenTB = value;
					this.SendPropertyChanged("TenTB");
					this.OnTenTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong_TB", DbType="Int")]
		public System.Nullable<int> SoLuong_TB
		{
			get
			{
				return this._SoLuong_TB;
			}
			set
			{
				if ((this._SoLuong_TB != value))
				{
					this.OnSoLuong_TBChanging(value);
					this.SendPropertyChanging();
					this._SoLuong_TB = value;
					this.SendPropertyChanged("SoLuong_TB");
					this.OnSoLuong_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThietBi_PhanThietBi", Storage="_PhanThietBis", ThisKey="MaTB", OtherKey="MaTB")]
		public EntitySet<PhanThietBi> PhanThietBis
		{
			get
			{
				return this._PhanThietBis;
			}
			set
			{
				this._PhanThietBis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThietBi_PhanThietBi_LT", Storage="_PhanThietBi_LTs", ThisKey="MaTB", OtherKey="MaTB")]
		public EntitySet<PhanThietBi_LT> PhanThietBi_LTs
		{
			get
			{
				return this._PhanThietBi_LTs;
			}
			set
			{
				this._PhanThietBi_LTs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanThietBis(PhanThietBi entity)
		{
			this.SendPropertyChanging();
			entity.ThietBi = this;
		}
		
		private void detach_PhanThietBis(PhanThietBi entity)
		{
			this.SendPropertyChanging();
			entity.ThietBi = null;
		}
		
		private void attach_PhanThietBi_LTs(PhanThietBi_LT entity)
		{
			this.SendPropertyChanging();
			entity.ThietBi = this;
		}
		
		private void detach_PhanThietBi_LTs(PhanThietBi_LT entity)
		{
			this.SendPropertyChanging();
			entity.ThietBi = null;
		}
	}
}
#pragma warning restore 1591
